service: serverless-framework-node
provider:
  name: azure
  region: Brazil South
  runtime: nodejs10
plugins:
  - serverless-azure-functions
  - serverless-express
package:
  exclude:
    - local.settings.json
    - host.json
functions:
  consulta-cnpj-api:
    handler: handler.handler
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
          methods:
            - post